### ISSUE TITLE
--dot doesn't escape double quotes

### ISSUE THREAD

**Issue by grifx** [ricomariani/CG-SQL-author#32] opened 2023-09-23 13:04 UTC
There is an issue with the way we generate the dot output.

Example:
```
strb [label = "'The dot AST output does not escape double quotes "x".'" shape=plaintext]
```

How to reproduce
```
<<'EOF' | sources/out/cql --dot --hide_builtins | dot
DECLARE PROC printf NO CHECK;

CREATE PROC entrypoint ()
BEGIN
  call printf("The dot AST output does not escape double quotes \"x\".");
END;
EOF
```

Line causing this issue: sources/cql.y:2377

https://github.com/ricomariani/CG-SQL-author/blob/3a39e272fd3f784f4ceca382154f5c4ba4df5390/sources/cql.y#L2382
```

digraph parse {
    stmt_list0 [label = "stmt_list" shape=plaintext]
    stmt_list0 -> declare_proc_no_check_stmt1;
    declare_proc_no_check_stmt1 [label = "declare_proc_no_check_stmt" shape=plaintext]
    declare_proc_no_check_stmt1 -> str2;
    str2 [label = "printf" shape=plaintext]
    _1 [label = "⏚" shape=plaintext]
    declare_proc_no_check_stmt1 -> _1;
 stmt_list0 -> stmt_list3;
    stmt_list3 [label = "stmt_list" shape=plaintext]
    stmt_list3 -> create_proc_stmt4;
    create_proc_stmt4 [label = "create_proc_stmt" shape=plaintext]
    create_proc_stmt4 -> str5;
    str5 [label = "entrypoint" shape=plaintext]
 create_proc_stmt4 -> proc_params_stmts6;
    proc_params_stmts6 [label = "proc_params_stmts" shape=plaintext]
    _6 [label = "⏚" shape=plaintext]
    proc_params_stmts6 -> _6;
 proc_params_stmts6 -> stmt_list7;
    stmt_list7 [label = "stmt_list" shape=plaintext]
    stmt_list7 -> call_stmt8;
    call_stmt8 [label = "call_stmt" shape=plaintext]
    call_stmt8 -> str9;
    str9 [label = "printf" shape=plaintext]
 call_stmt8 -> arg_lista;
    arg_lista [label = "arg_list" shape=plaintext]
    arg_lista -> strb;
    strb [label = "'The dot AST output does not escape double quotes "x".'" shape=plaintext]
    _a [label = "⏚" shape=plaintext]
    arg_lista -> _a;
    _7 [label = "⏚" shape=plaintext]
    stmt_list7 -> _7;
    _3 [label = "⏚" shape=plaintext]
    stmt_list3 -> _3;
}

Error: <stdin>: syntax error in line 29 near '"'
```

**Comment by ricomariani** [comment] 2023-09-23 13:12
Except for Mohsen, who wrote it, you could be the first person to actually use the .dot output.

the quote escaping code did not exist when this was written.  I'll fix it up.

R
________________________________
From: Joris Garonian ***@***.***>
Sent: Saturday, September 23, 2023 6:04 AM
To: ricomariani/CG-SQL-author ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ricomariani/CG-SQL-author] --dot doesn't escape double quotes (Issue #32)


There is an issue with the way we generate the dot output.

Example:

strb [label = "'The dot AST output does not escape double quotes "x".'" shape=plaintext]


How to reproduce

<<'EOF' | sources/out/cql --dot --hide_builtins | dot
DECLARE PROC printf NO CHECK;

CREATE PROC entrypoint ()
BEGIN
  call printf("The dot AST output does not escape double quotes \"x\".");
END;
EOF


Line causing this issue: sources/cql.y:2377

https://github.com/ricomariani/CG-SQL-author/blob/3a39e272fd3f784f4ceca382154f5c4ba4df5390/sources/cql.y#L2382


digraph parse {
    stmt_list0 [label = "stmt_list" shape=plaintext]
    stmt_list0 -> declare_proc_no_check_stmt1;
    declare_proc_no_check_stmt1 [label = "declare_proc_no_check_stmt" shape=plaintext]
    declare_proc_no_check_stmt1 -> str2;
    str2 [label = "printf" shape=plaintext]
    _1 [label = "⏚" shape=plaintext]
    declare_proc_no_check_stmt1 -> _1;
 stmt_list0 -> stmt_list3;
    stmt_list3 [label = "stmt_list" shape=plaintext]
    stmt_list3 -> create_proc_stmt4;
    create_proc_stmt4 [label = "create_proc_stmt" shape=plaintext]
    create_proc_stmt4 -> str5;
    str5 [label = "entrypoint" shape=plaintext]
 create_proc_stmt4 -> proc_params_stmts6;
    proc_params_stmts6 [label = "proc_params_stmts" shape=plaintext]
    _6 [label = "⏚" shape=plaintext]
    proc_params_stmts6 -> _6;
 proc_params_stmts6 -> stmt_list7;
    stmt_list7 [label = "stmt_list" shape=plaintext]
    stmt_list7 -> call_stmt8;
    call_stmt8 [label = "call_stmt" shape=plaintext]
    call_stmt8 -> str9;
    str9 [label = "printf" shape=plaintext]
 call_stmt8 -> arg_lista;
    arg_lista [label = "arg_list" shape=plaintext]
    arg_lista -> strb;
    strb [label = "'The dot AST output does not escape double quotes "x".'" shape=plaintext]
    _a [label = "⏚" shape=plaintext]
    arg_lista -> _a;
    _7 [label = "⏚" shape=plaintext]
    stmt_list7 -> _7;
    _3 [label = "⏚" shape=plaintext]
    stmt_list3 -> _3;
}

Error: <stdin>: syntax error in line 29 near '"'

**Comment by ricomariani** [comment] 2023-09-23 14:15
Fixed in https://github.com/ricomariani/CG-SQL-author/commit/8516b39e7a98e571ab064a340ab6d50b8a46508b

In Mohsen's defense, at the time he wrote that code none of that logic existed.  It turns out there are lots of tricky encodings the compiler had to do and it built the muscle to do these over its life.  At this point you can do whatever you need with quoted strings pretty easily.  Back then there was nothing.  Even character buffers for interim output didn't exist yet.  Not even the EXTRACT macros existed... so they were obviously not used.

**Closed by ricomariani** 2023-09-23 14:15 UTC
